server:
  port: 8090
  servlet:
    context-path: /weather-provider

openweather:
  api:
    url: http://api.openweathermap.org/data/2.5/weather
    key: 1cdf5202160747e1565f19c1e1276e8e

cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: ENC(AQ90BEl4kjQqnEnwgBcnq+R4lHvrsF9bpHLtpqYfr11pT7PjalOGbpfu5fzazjBUHOPABz6ZlQF9jq1lU1QHQA==)
      secret-key: ENC(nNMtnKLivIWm2gaxo2/9u4uhrsfpi/Q3OvNNO8aKAgnBLCM8TVe5/6a4jY5clna/4zAR2Li9KymhdAAs0qmK2H6jd3cgrcYF8q0DHt3OxyI=)
    stack:
      auto: false
    weather-queue: https://sqs.us-east-2.amazonaws.com/267356554041/weather-persistence-command

logging:
  level:
    com:
      amazonws:
        util:
          EC2MetadataUtils: error
jasypt:
  encryptor:
    password: <INSERT_PASSWORD>
